name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Create pages directory structure
        run: |
          mkdir -p ./pages-output

          # Copy Next.js build output
          cp -r ./out/* ./pages-output/ 2>/dev/null || :

          # Create projects directory and copy HTML projects
          mkdir -p ./pages-output/projects

          # Copy each project with clean URLs
          if [ -d "./Projects/GBL" ]; then
            cp -r "./Projects/GBL" "./pages-output/projects/gbl"
          fi

          if [ -d "./Projects/Time_Management" ]; then
            cp -r "./Projects/Time_Management" "./pages-output/projects/time-management"  
          fi

          if [ -d "./Projects/Time_Management_Main" ]; then
            cp -r "./Projects/Time_Management_Main" "./pages-output/projects/time-management-main"
          fi

          if [ -d "./Projects/rock-climbing-raw-v2ojS82U" ]; then
            cp -r "./Projects/rock-climbing-raw-v2ojS82U" "./pages-output/projects/rock-climbing"
          fi

          # Create index.html files for directory navigation if needed
          echo "GitHub Pages deployment completed successfully" > ./pages-output/projects/README.txt

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages-output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
